### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#161]
Not sure whether this is something you guys care about, as I assume Brigade is an all-Unix shop, but it would be great if this tool supported Windows so that users in corporate environments (read: me) could share it with their coworkers.

Obviously this would require some fairly massive changes, so I understand if this isn't something you want to pursue.

**Comment by sds** [comment]
I think it would be awesome if Overcommit supported Windows. The reality in the past was that since none of the core contributors to Overcommit used Windows, it was hard to justify adding support since no one would be there to support it.

Your contributions over the past few weeks suggest that you care about this tool.

If you are willing to research and explore what's involved in adding Windows support, drive the implementation, and maintain it, I would be willing to merge your pull requests. My hunch is that you would simply need to add some special cases to Overcommit's low-level `git` and process management helpers to get most of the way there. 

Some _known_ unknowns from my perspective (these may turn out to not be an issue, but as I don't use Windows I can't speak to them):

* I'm not sure how Ruby threading support differs for Windows, so if we end up supporting parallelized hook runs this might get tricky (might have to just disable it for Windows)
* I'm not sure how Windows handles process signals, so a lot of the logic we have in place for gracefully handling Ctrl-C (which sadly doesn't have any tests) might need to have an alternate Windows implementation
* I'm not sure if there are any gotchas with `Process.detach` and `Process.spawn` on Windows. Specifically whether `Overcommit::Utils.execute_in_background` will work
* We use the [`childprocess`](https://github.com/jarib/childprocess) gem to manage reading standard out/error streams and obtaining exit codes of processes. I'm not sure if our use of the gem is cross-platform compatible, so there might be some work required in the `Overcommit::Subprocess` helper class

In light of the above, there's probably going to need to be some work to add more tests verifying the existing behavior of Overcommit so we ensure existing functionality isn't broken once we start going down this path.
