### ISSUE TITLE
Vim/Fugitive integration

### ISSUE THREAD

**Issue by khani3s** [brigade/overcommit#184]
I would like to get the overcommit errors inside vim when I commit via fugitive. The ideia its put the overcommit errors in the vim quickfix window. Can I redirect the overcommit errors to some file ?

**Comment by sds** [comment]
Hey @khani3s, thanks for your interest in `overcommit`!

There shouldn't be anything stopping you from using `overcommit` within Fugitive. Git hooks write to the standard out stream, so it should work with any tools that already integrate with git.

If that's not the case, let us know!

**Comment by lfv89** [comment]
That's not the case, at least for me. That's everyhing that I see:

![screen shot 2017-05-23 at 16 53 43](https://cloud.githubusercontent.com/assets/816490/26373576/6c9277ce-3fd8-11e7-8500-d735b61ddedf.png)

Any thoughts?

Thanks!

**Comment by sds** [comment]
Hey @lfv89,

This appears to be an issue with Fugitive. I'm not sure what action you tried to carry out, but it looks like in some cases it will truncate the output to the first line, e.g. https://github.com/tpope/vim-fugitive/blob/d6e7e20123ef3892c041e4d9fbaf67a68b144a94/plugin/fugitive.vim#L1506

It's hard to provide any more context since I don't know what version of Fugitive you're running, but I think this issue would be best posted to that project instead. Thanks!

**Comment by lfv89** [comment]
Yes, already working on a solution.

Gonna post here when it's fixed, thanks!.
