### ISSUE TITLE
Add section that documents the hooks?

### ISSUE THREAD

**Issue by lencioni** [brigade/overcommit#189]
I think we used to include a list of the hooks in the readme, but somewhere along the way that seems to have been removed. In any case, now that overcommit has grown, it might be really useful for people to have a place they can reference what all of the hooks are with additional information such as links to the relevant tools. This would help people understand what overcommit is capable of and serve as a useful linking-to point from other projects back to overcommit.

Some of this came up while discussing adding a link to overcommit from reek: https://github.com/troessner/reek/pull/457

I imagine something similar to what we are doing over at scss-lint for documenting the different linters would be a good place to start: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

Thoughts?

**Comment by sds** [comment]
Documenting all available hooks would be great, however it does come with a cost.

My experience with `scss-lint` is that people tend to not write good, clear documentation when submitting pull requests. Fortunately, I think for most Overcommit hooks the documentation would be as simple as linking to the related project.

This section should live outside of the main README, as it will get large quickly. I propose a general README in `lib/overcommit/hook` (linked to from the main README) that describes each type of hook, what kind of checks make sense for that type, and how to write hooks for them. Each section within that document can then link to `lib/overcommit/hook/<hook-type>/README.md` which documents all hooks for that particular type.

**Comment by mvz** [comment]
Hi, chipping in as one of the participants in the discussion at https://github.com/troessner/reek/pull/457.

@sds, I would not separate out the list of hooks into separate READMEs per hook type. The point of [my comment](https://github.com/troessner/reek/pull/457#issuecomment-94250186) was to avoid having to dig through several layers to find a particular hook.

As an example, say I'm interested in overcommit because I would like to run reek on every commit. In that case, it's much easier to just search for reek in one file, and then finding what kind of hook is needed and how to enable it, than it is to first think by myself what kind of hook might be sensible and then going to the corresponding README to see if reek might be listed there.

As a start, you could just link each of the hook names to the relevant class. There would be no need to document the hook fully in the main README. Having a list of all the hooks in one place would be the main advantage.

**Comment by sds** [comment]
Those are fair points, @mvz. I like the idea of just linking to the hook's source code. It results in fewer places you have to add documentation when adding new hooks, and the source code can double as the official documentation (single source of truth!).

Given this will reduce the list to act more like a table of contents, I'd even be in favor of putting it in the main README. Explanations of each type of hook and when their use makes sense probably also makes sense to store there. Given most developers are not intimately familiar with git hooks it probably makes sense to take the time to educate them.

**Comment by sds** [comment]
The [Built-In Hooks](README.md#built-in-hooks) section of the README now includes a listing of all currently available hooks, as well as a quick indication of which are enabled by default. See dbc9f8e862bba760e39dbbbcc7139990ea479abc for details.

We'll start treating the hook implementations as the source of documentation.

**Comment by mvz** [comment]
Nice. Thanks!
