### ISSUE TITLE
Define and apply consistent hook naming scheme

### ISSUE THREAD

**Issue by lencioni** [brigade/overcommit#199]
I've noticed some inconsistencies in how the hooks are named.

For instance, "RuboCop" is the name of the tool but our hook is written like "Rubocop"--I assume because `rubocop` is the command that is executed. However, "JSHint" is the name of the tool and `jshint` is the executable, but our hook is written like "JsHint".

This was brought up in: https://github.com/bbatsov/rubocop/pull/1811#discussion_r29310761

It isn't entirely clear to me what the naming scheme is or should be for overcommit hooks. This information would be good to include in the README.md or in a CONTRIBUTING.md file.

**Comment by sds** [comment]
I've taken a stab at describing the naming convention in c7be5f1ad0ecf8353f6e3346642fc7554d0d5243 by updating the `CONTRIBUTING.md` file.

It may be worth changing the convention to just be whatever the proper name of the upstream project is, but that might get awkward with projects that intentionally start with lowercase letters, since Ruby requires classes to start with an uppercase letter.
