### ISSUE TITLE
Hooks specified in .overcommit.yml ignored/not ran 

### ISSUE THREAD

**Issue by seanknox** [brigade/overcommit#233]
I'm on a fresh machine with a repo that uses Overcommit. Per my config file [here](https://gist.github.com/seanknox/d3059c7864b8411cd2fc), I'm using a handful of precommit hooks. 

- When I commit a file that multiple hooks would warn about, Overcommit doesn't appear to run anything. - Manually running `overcommit -r`, a couple hooks are run, but others are not.
- If I enable all hooks (as opposed to per-hook enabling), all hooks appear to run, including the ones I specifically enabled in the first two examples (which didn't run previously).

I think I'm overlooking something simple. Any help is appreciated.

**Comment by seanknox** [comment]
(Note to self: opening issues on weekends generally a bad idea, before Pride weekend, especially bad)

**Comment by sds** [comment]
Hey @seanknox,

First of all, `Rubocop` is spelt `RuboCop`, so that's one issue.

However, I'm not clear on what exactly the problem is. When I use the configuration you provided, editing a `.rb` file or `.yml` file causes the `RuboCop` and `YamlSyntax` hooks to be called appropriately.

Are you on the latest version of Overcommit? Are you sure you've set up your hooks so they have the extensions these hooks are expecting?

**Comment by seanknox** [comment]
@sds spelling—this is why we pair. :) Fixing `RuboCop`'s spelling did the trick. Thanks.
