### ISSUE TITLE
Imperative present tense CommitMsg hook

### ISSUE THREAD

**Issue by garyttierney** [brigade/overcommit#274]
Hi,

Recently came across overcommit and it's an invaluable tool in forcing myself to write better commits! However, I'd like to add a CommitMsg hook which checks (with a simple heuristic, at least) that the message is written in [imperative present tense](http://git.kernel.org/cgit/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n112).

It'd work by checking for common verbs (add, remove, refactor, fix) and use a regular expression to check if the summary or body contains something like `(?:add|remov|refactor|fix|delet)(?:ed|ing)`.

Is this something which would be suitable for merging back upstream?

**Comment by sds** [comment]
We've thought about this, and the problem is that it's difficult to come up with a comprehensive list, and we'd also be biasing towards the English language.

For example, if I run `git log --oneline | cut -d' ' -f2 | sort | uniq` on a large repository that follows this convention, I get a large number of words that aren't actual "words" per se, but which are imperative present tense and the meaning is clear.

For example, there are a number of words you can "create" through the use of the hyphen, e.g. "Auto-expand", "Re-render", etc. There are also situations where a word is both a noun and a verb, e.g. "Mock", so it's difficult to know if it's used in the correct tense or not ("Mock was not working" versus "Mock external endpoint correctly").

Thus I think you'd be surprised how often your commits would be flagged as not imperative even when they were. Perhaps there's an argument here for forcing developers to use specific verbs, but that seems like a bit much to me personally.

I think an implementation that would have actual general use would expose a configuration that would allow you to specify a list of regexes of allowed commit message prefixes. Given how often this is going to be updated, I'd rather not have the Overcommit project itself maintain that list, so I would encourage you to implement it yourself for your own projects.

P.S. If you know of any [NLP](https://en.wikipedia.org/wiki/Natural_language_processing) projects that can identify the tense of a sentence, perhaps we can reconsider this, but my understanding is that you'll still run into edge cases pretty frequently thanks to the quirks of language.

**Comment by lencioni** [comment]
I echo what @sds said, but I also think you might be able to get a good enough solution by using a blacklist method that just looks at the ending of the first word. In my experience, at least in English, words ending in "ed" or "es" seem to be the main offenders here (e.g. "Fixes" and "Fixed" vs. "Fix"). Certainly not a perfect solution, but might be good enough.
