### ISSUE TITLE
Question about BundleCheck hook

### ISSUE THREAD

**Issue by deivid-rodriguez** [brigade/overcommit#293]
Running this hook through the `--run` option fails whenever `Gemfile.lock` has changes, even if they match the `Gemfile`.

What's the rationale behind this? In particular, what are [these lines](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/bundle_check.rb#L19-L22) for? Removing them doesn't break any tests, so whatever they are doing, it's untested. Isn't the part of the hook running `bundle check` enough?

Thanks.

**Comment by deivid-rodriguez** [comment]
Added a PR to remove this in #294 since I already had the changes locally.

**Comment by trotzig** [comment]
I think this check is to make sure that you don't forget to commit the Gemfile.lock file. The check fails if you have added changes in Gemfile to the git index, but not added Gemfile.lock. There wasn't much info in the commit that added the lines though (101fa044), perhaps @sds can clarify? 

We might want to add a test for this, or at least a comment explaining how it works.

**Comment by sds** [comment]
The hook was written to work in the context of a pre-commit hook. Thus it first runs `bundle check` which will update the `Gemfile.lock` accordingly (note that if you change `Gemfile` and then run `bundle check` it will update the `Gemfile.lock` without raising an error).

Thus the hook then checks to see if the `Gemfile.lock` has changed as a result of running `bundle check`.

In the case where you are invoking the hook via the `--run` flag, the issue is that we haven't written the hook to be aware of this context. We would have to rewrite it to store a copy of the old `Gemfile.lock`, run `bundle check`, and then compare that to the new version to see if a change occurred (and thus not rely on the output of `git diff --quiet -- Gemfile.lock`).

**Comment by deivid-rodriguez** [comment]
Thanks to both! Yes, this usually bites me when I run the check with the `--run` flag.

I misunderstood what `bundle check` does, I thought it would just check whether `Gemfile.lock` is in sync with `Gemfile` (but not update anything). So as you describe it, it's the same as `bundle install` but without installing any gems? I wonder how that's useful and when I would want the `bundle check` behaviour.

**Comment by sds** [comment]
The behavior is valuable for ensuring that if you are tracking both your `Gemfile` and `Gemfile.lock` in source control that you are alerted when they are not in sync with each other. 

I don't think `bundle check` is terribly useful outside of this specific context, so I agree it's a bit odd. In a hook it makes sense since we don't want to install gems during the hook run. 

In any case, I've updated the hook to work around the case you're running into in ed0fc9c6b2a89f1ea19797741ff3341eefefb978.

**Comment by deivid-rodriguez** [comment]
Thanks @sds ! :+1:
