### ISSUE TITLE
Appveyor badge uses `sds/overcommit` rather than `brigade/overcommit`

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#314]
The Appveyor badge links to the `sds/overcommit` project, when it should really link to `brigade/overcommit`. As it is, the badge is only accurate when @sds's `master` is up-to-date with the main repo.

Currently there is no `brigade/overcommit` project on Appveyor, so the first step would be to create one.

Related: #299

**Comment by sds** [comment]
When I originally set this up, I was unable to create `brigade/overcommit` as a project since Appveyor uses a naming convention that ties itself to the user who originally created the project (i.e. they don't support the concept of an organization from what I can see).

Thus `sds/overcommit` was born. However, it looks like at some point (or perhaps always) the URL changed to `sds/overcommit-v4g0l`. I have no idea where this came from.

In any case, I now see that you can create an organization account by registering a [new account via email](http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations), and _then_ associating a GitHub organization.

I've done that and updated the badge in a52149d2c3f2a4c75b57596823fd54c0e933ab95.
