### ISSUE TITLE
Overcommit crashes in Ruby 2.3.0 with rvm

### ISSUE THREAD

**Issue by derwiki-everlane** [brigade/overcommit#320]
```
$ overcommit --install
/Users/adam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3feaa3655a18 overcommit-0.30.0> (NoMethodError)
        from /Users/adam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /Users/adam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /Users/adam/.rvm/gems/ruby-2.3.0/gems/overcommit-0.30.0/bin/overcommit:3:in `<top (required)>'
        from /Users/adam/.rvm/gems/ruby-2.3.0/bin/overcommit:23:in `load'
        from /Users/adam/.rvm/gems/ruby-2.3.0/bin/overcommit:23:in `<main>'
        from /Users/adam/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/adam/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I've tried installing from rubygems.org as well as building locally. Let me know if you need additional info to reproduce/troubleshoot.

**Comment by sds** [comment]
Hey @derwiki-everlane, I can't reproduce this with Ruby 2.3.0 installed via `rbenv` on either Mac OS X or CentOS 7. Looking at the stack trace provided I'm skeptical this is an issue with Overcommit since it's failing on the line `require 'overcommit/cli'`, which means there's an internal Ruby issue here.

It looks like https://github.com/rubygems/rubygems/issues/1420 is relevant to your particular issue. Perhaps you should try downgrading Rubygems as suggested in https://github.com/rubygems/rubygems/issues/1420#issuecomment-167125657. 

Otherwise, I don't think there's anything Overcommit can do here to help. I (only half-jokingly) suggest you switch to `rbenv` instead of `rvm`, as I see these kinds of issues only with the latter.

**Comment by fatroller** [comment]
Yes, I'm getting the same error while running a rubber -h command. I'm using rvm on Mac OS X 10.11.2.

Any assistance would be appreciated ?

    $ rubber -h
    /Users/uname/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd0a6037e2c rubber-3.2.0> (NoMethodError)
    from /Users/uname/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
    from /Users/uname/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /Users/uname/.rvm/gems/ruby-2.3.0@newapp/gems/rubber-3.2.0/bin/rubber:13:in `<top (required)>'
    from /Users/uname/.rvm/gems/ruby-2.3.0@newapp/bin/rubber:23:in `load'
    from /Users/uname/.rvm/gems/ruby-2.3.0@newapp/bin/rubber:23:in `<main>'
    from /Users/uname/.rvm/gems/ruby-2.3.0@newapp/bin/ruby_executable_hooks:15:in `eval'
    from /Users/uname/.rvm/gems/ruby-2.3.0@newapp/bin/ruby_executable_hooks:15:in `<main>'

**Comment by sds** [comment]
Hey @fatroller,

As I said above, this is not a problem caused by Overcommit (as is evidenced by the fact that you hit this when running an unrelated tool, `rubber`).

My recommendation is to try what's mentioned in https://github.com/rubygems/rubygems/issues/1420, specifically downgrading Rubygems on your machine: https://github.com/rubygems/rubygems/issues/1420#issuecomment-167125657.

**Comment by astorre88** [comment]
Why do you think we should downgrade Ruby version if overcommit fails only?))))

**Comment by danarrington** [comment]
For anyone in the future who finds this, it seems it may have been an issue with rvm + rubygems 2.5.1.  Upgrading rubygems (to 2.6.7) resolved it for me.
