### ISSUE TITLE
Add PreCommit hook to disallow committing to specified branches

### ISSUE THREAD

**Issue by lencioni** [brigade/overcommit#327]
I work in some projects where I never want to commit to master, but I sometimes mistakenly do this and forget about it, which causes extra friction later when I rebase or create new branches based off of master. It would be nice if I had a hook that prevented me from doing this.

**Comment by jawshooah** [comment]
If this is implemented, it should probably include a parameter `allow_merge` in case you want to exclusively allow merge commits.

**Comment by jawshooah** [comment]
After some searching, I haven't found a way to reliably determine whether a pending commit is a merge or not. Seems some people are using the presence of `.git/MERGE_MSG` as an indicator, but unfortunately we've already stored and wiped that file in `Overcommit::GitRepo#store_merge_state` by the time pre-commit hooks are run.

@lencioni Is this still a hook you'd like to see implemented? Since we can't reliably determine whether a commit is a merge during `pre-commit`, you'll only be able to merge in changes via a web interface or by skipping the `ForbiddenBranches` hook.

**Comment by lencioni** [comment]
Thanks for digging into this @jawshooah! 

> unfortunately we've already stored and wiped that file in `Overcommit::GitRepo#store_merge_state` by the time pre-commit hooks are run.

I don't have much context there, but would it be possible to check for the indicator file and then set some context that we can use in pre-commit hooks?

I think the hook is worth implementing even if we can't make it work smoothly with merges, since many people probably never or rarely merge into certain branches locally.

**Comment by jawshooah** [comment]
> would it be possible to check for the indicator file and then set some context that we can use in pre-commit hooks?

Definitely, but I'm wary of polluting the API any more than necessary, particularly for the sake of a single hook. That said, it may be desirable in some future hook implementation to know whether or not a pending commit is a merge, in which case we can revisit. @sds, feel free to weigh in if you have any strong feelings either way.

**Comment by lencioni** [comment]
Yes, I totally agree with not polluting the API any more than necessary, especially for the sake of a single hook. Let's let this stew for a while and see if any more use cases shake out.
