### ISSUE TITLE
which dictionary to use with SpellCheck

### ISSUE THREAD

**Issue by deepak** [brigade/overcommit#337]
which dictionary to use with `SpellCheck`
I downloaded a dictionary from https://sourceforge.net/projects/hunspell/files/Spelling%20dictionaries/en_US/

for instance i catches that `overcommitel` is a bad spelling 

> Potential misspelling: overcommitel. Suggestions: overcommitment, overcomplexity, overcomplicated, overcompensate, overcomer, overcapitalize

but flags `rubygem` also as a misspelling

> Potential misspelling: rubygem. Suggestions: ruby gem, ruby-gem, ruby, Ruby, grubby, Rubicon, ribcage

does anyone maintain a coding focused dictionary :-)
and where are people getting their dictionaries from ? can people share please ?

**Comment by sds** [comment]
I'm not familiar with the collection of dictionaries available for `hunspell`. The author of the `SpellCheck` hook @jawshooah might have some suggestions, but it's likely going to be the case that you'll have to maintain one yourself. It's simply too difficult to keep a dictionary up-to-date with the plethora of tech jargon and technology names that get introduced every day (in my opinion, anyway; happy to be shown otherwise).

**Comment by jawshooah** [comment]
Sorry @deepak, I'm not aware of any specialized programming dictionaries.

**Comment by jawshooah** [comment]
Note, though, that as long as you keep the `SpellCheck` hook set to warn and not fail, it shouldn't be an impedance to committing, and was never intended to be. It's simply there to warn you of *potential* misspellings, you're free to disregard them as you please.
