### ISSUE TITLE
Overcommit causes GPG signing prompt to appear twice

### ISSUE THREAD

**Issue by monfresh** [brigade/overcommit#372]
Hi. I just installed this gem on a project and it works great. Thanks for developing it. The only issue I have with it so far is that it is causing the GPG prompt to appear twice. I have configured my repo to sign all commits with my GPG key (https://help.github.com/articles/signing-commits-using-gpg/).

Before installing overcommit, I was only prompted once for my GPG passphrase. And with `gpg-agent` running in the session, I was not prompted for my passphrase for every commit. After installing overcommit, I am either prompted twice in a row for my passphrase (when gpg-agent is not running), or once when gpg-agent is running.

Do you know if there's a way around this?

**Comment by sds** [comment]
Hey @monfresh,

Sorry for the slow response here. I can indeed reproduce this undesirable behavior. 

The problem was that the stash commits created by the pre-commit hook (to save your work before running hooks) were also being signed. I've fixed this in 62132a6996b20e76757a8e4975ef20e89b707b0d.

Thanks for the report!

**Comment by monfresh** [comment]
Thanks for fixing this! I will give the new version a try.
