### ISSUE TITLE
Prepush Mocha Tests On Protected Branches

### ISSUE THREAD

**Issue by AlexDar** [brigade/overcommit#379]
I don't fully understand from the docs how to make custom hooks so I may be missing something _obvious_. Ultimately I'd like to run `npm run mocha` on prepush on the protected branches (I'm not sure if this is supported?). `ForbiddenBranches` and `Standard` work as expected however I can't get mocha to work. I suspect it's because it's not one of the defaults provided by overcommit. Executing `overcommit -r` gives me the following error:

    /Users/user/.rvm/gems/ruby-2.2.1/gems/overcommit-0.33.0/lib/overcommit/hook_signer.rb:39:in`hook_path': Hook must specify a `required_executable` or `command` that is tracked by git (i.e. is a path relative to the root of the repository) so that it can be signed 

My `package.json`:

    "mocha": "./node_modules/.bin/mocha --reporter spec",
    "test": "npm run mocha" 

    
My `.overcommit.yml`:

    PreCommit:
      ForbiddenBranches:
        enabled: true
        required: true
        quiet: false
        description: 'Check for commit to forbidden branches (master, develop)'
        branch_patterns: ['master', 'develop']

      Standard:
       description: 'Check JS Standard Style...'
       enabled: true
       required: true
       quiet: false
       required_executable: 'standard'
       install_command: 'npm install -g standard'    
       exclude: &default_excludes
          - 'server/node_modules/**/*'
          - 'vendor/**/*'

      Mocha:
        description: 'Running Mocha tests...'
        enabled: true
        required: true
        quiet: false
        required_executable: './node_modules/mocha/bin/mocha'
        install_command: 'npm install -g mocha'
        command: ['npm', 'run', 'mocha', '--']

**Comment by sds** [comment]
Hey @AlexDar,

To clarify `overcommit --run` executes your `pre-commit` hooks, not `pre-push` hooks (though I think you meant `pre-commit` when you said "prepush").

Assuming that is the case, remember that `required_executable` needs to be the entire command, since in the context of a hook run we are passing any arguments/STDIN that are passed by git into your script.

Therefore you need to have a helper script (with executable permissions):

```bash
# script/my-mocha-script
#!/bin/bash
npm run mocha --
```

...and then in your `.overcommit.yml`:

```yaml
Mocha:
    ...
    required_executable: './script/my-mocha-script'
```

Hope that helps.
