### ISSUE TITLE
0.34.0 Release Install Broken on Windows

### ISSUE THREAD

**Issue by smurawski** [brigade/overcommit#387]
The gem package for 0.34.0 appears to respond to symlink? (in rubygems/package.rb:386) which is not implemented on Windows.

**Comment by sds** [comment]
@smurawski Can I get you to include a little more information? There were no Windows-related changes to Overcommit between 0.33.0 and 0.34.0.

A full stack trace would be helpful in providing some context. Thanks!

**Comment by smurawski** [comment]
@sds Thanks for the quick response ->

Failures with stack traces ->

https://ci.appveyor.com/project/chef/ohai/build/master-841/job/br0tgl2fvaaa6bsr#L87
and
https://ci.appveyor.com/project/test-kitchen/test-kitchen/build/master-535#L126

The bundler install blows up on overcommit 0.34.0.  When I pin to 0.33.0, the `bundle install` succeeds.  I was able to replicate locally as well and if I break in just before the error it shows the overcommit package responding to `symlink?` in rubygems/package.rb about line 386.

**Comment by sds** [comment]
It's odd that you were seeing this problem for only Overcommit 0.34.0. You should also be seeing it for any other version given where that code is erroring.

The Overcommit gem has symlinks in its `template-dir`, which hasn't been a problem. It looks like some changes to how RubyGems creates the gem tarball (specifically with regards to symlinks) may have caused this to start breaking: https://github.com/rubygems/rubygems/pull/1209

So due to a bug in an older RubyGems version, Overcommit 0.33.0 was built with these symlinks auto-converted to regular files, thus there was no problem. With newer versions they will be preserved as symlinks, hence why we were seeing this on 0.34.0 only.

Fix forthcoming. Thanks for the report!

**Comment by sds** [comment]
Fixed in 5bf372fd8ba543f90aeffee0e8d87bed4c1898e4.

**Comment by smurawski** [comment]
Thank you @sds !!!  Much appreciated and love the quick turnaround.

**Comment by sds** [comment]
[0.34.1](https://github.com/brigade/overcommit/releases/tag/v0.34.1) has been released
