### ISSUE TITLE
Hook to check versions match between Gemfile.rb and overcommit_gems.rb

### ISSUE THREAD

**Issue by abaldwin88** [brigade/overcommit#412]
The readme recommends creating a separate gemfile to decrease Overcommit's startup delay.  This works great but it's easy to get versions out of sync between Overcommit's gemfile and the primary gemfile.  

For example in our project we always want the version of Rubocop in `Gemfile.lock` to match the Rubocop version in `.overcommit_gems.rb.lock`.  That way developers will get the same results between `bundle exec rubocop` and `git commit` with the Rubocop hook enabled.

It's easy to update the primary GemFile while forgetting to update Overcommit's gemfile.  I think this is an excellent target for adding a built-in PreCommit hook to check that the gemfiles match.  I am planning to write it and submit a PR.  However I wanted to check with the Overcommit team first.  Would this be a good feature to add?

**Comment by sds** [comment]
You can get most of the way there by using `eval_gemfile` in your `Gemfile` so you can reference `.overcommit_gems.rb`.

This will result in your hooks failing if the `.overcommit_gems.rb.lock` file doesn't match the `.overcommit_gems.rb`, but your `Gemfile` (and thus `Gemfile.lock`) will use the same versions as those specified in `.overcommit_gems.rb.lock`.

For example:

**Gemfile**
```ruby
gem 'rails'

group :development do
  eval_gemfile File.join(File.dirname(__FILE__), '.overcommit_gems.rb')
end
```

**.overcommit_gems.rb**
```ruby
# Need to use a source block since this is included by another Gemfile, and
# Bundler doesn't like two top-level `source` definitions unless they are blocks.
source 'https://rubygems.org' do
  gem 'bundler-audit', '0.5.0', require: false
  gem 'haml_lint', '0.18.1', require: false
  gem 'overcommit', '0.35.0', require: false
  gem 'rubocop', '0.42.0', require: false
  gem 'scss_lint', '0.49.0', require: false
end
```

Note that you need to define explicit versions in `.overcommit_gems.rb` to ensure the versions are consistent between `Gemfile.lock` and `.overcommit_gems.rb.lock` (otherwise when you `bundle update ...` you'll find that the different list of gems between `Gemfile` and `.overcommit_gems.rb` may result in slightly different versions).

After updating `.overcommit_gems.rb`, simply run:
```bash
bundle install && bundle install --gemfile=.overcommit_gems.rb
```
...to update the lock files.

With this setup, your hook runs should fail the moment these two lock files fall out of sync, and thus you won't need to create a separate hook.

**Comment by abaldwin88** [comment]
@sds Cool.  That works well.  I think there's some slight drawbacks to that approach like not having all the versions listed in a single lock file but that's a pretty minor thing.

I did finish writing the hook but the specs are not completed yet.  If you feel like this feature is unnecessary though let me know so I can drop it.

**Comment by sds** [comment]
More than happy to accept a pull request with tests! I'm personally a fan of the approach I've outlined above but if others find a hook more useful then by all means let's make that approach available.

I'd like some clarification on this comment:

> I think there's some slight drawbacks to that approach like not having all the versions listed in a single lock file but that's a pretty minor thing.

I think this would still be a problem if you had a hook to catch this, unless I'm misunderstanding what you're referring to. Without explicitly defining versions in both `Gemfile` and `.overcommit_gems.rb`, it's possible that running `bundle install` at different times will result in different resolutions for a particular gem. A hook can catch a discrepancy after the fact, but you'll still need to manually update your version constraints in each file so that they resolve to the intended version.

With the approach outlined above, you define only the gems that are used by Overcommit in the `.overcommit_gems.rb` file (never explicitly in the `Gemfile` itself–they are included by `eval_gemfile` in `Gemfile`). Thus you have a single place for your gem versions to be defined. Including comments at the top of these gem files to remind developers that there are two locations to look is also a good idea.

Again, if you think a hook would be more helpful for your team's approach, would love a pull request!

**Comment by sds** [comment]
Closing this as it seems like the solution proposed in https://github.com/brigade/overcommit/issues/412#issuecomment-240603825 is "good enough" for this situation.
