### ISSUE TITLE
Why must somebody have a "last name"?

### ISSUE THREAD

**Issue by gerrywastaken** [brigade/overcommit#415]
https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/author_name.rb#L13

Is the intent to dissuade mononymous people (https://en.wikipedia.org/wiki/Mononymous_person), or those who simply wish to use a pseudonym, from making commits? If being able to get in contact with the person is the reason, then surely this is the purpose of the email.

![teller](https://cloud.githubusercontent.com/assets/71481/17648411/b143be5a-6257-11e6-97d9-9ff51bd0fd95.jpg)

Pictured above: Teller on the edge of tears, after overcommit rejected his name.

**Comment by sds** [comment]
Hey @gerrywastaken,

I appreciate the philosophical nature of this question. You are correct in that there is no legal requirement for a person to have a polynym (though your example isn't a great one: [Teller's license says "NFN Teller" where NFN = "No First Name"](http://www.imdb.com/name/nm0854418/bio)). 

There are many systems that expect a first and last name. We can complain that they should change, but it's often out of our control.

From a pragmatic perspective, I believe that the vast majority of development teams would prefer to enforce first + last name. It's valuable because names are easier to read than emails, and emails may obfuscate their name, e.g. `sds@gmail.com` doesn't tell you my name–how do you greet me when contacting me via message? 

I feel requiring first + last name also enforces a level of professionalism. Given the predisposition for our non-professional accounts to use mononymous user names (Twitter/Instagram/etc), encouraging their use seems inappropriate among professionals. Perhaps I'm old school in this regard.

However, given my belief that the vast majority of teams would prefer first + last name, I'm inclined to keep the default behavior as-is.

You are of course always welcome to disable the `AuthorName` pre-commit hook if you disagree with it!

**Comment by gerrywastaken** [comment]
@sds Thanks for the response

> It's valuable because names are easier to read than emails, and emails may obfuscate their name, e.g. sds@gmail.com doesn't tell you my name–how do you greet me when contacting me via message?

I wasn't suggesting allowing a commit with no name at all. Just that it would be great not to require **two** names.

> You are correct in that there is no legal requirement for a person to have a polynym (though your example isn't a great one: Teller's license says "NFN Teller" where NFN = "No First Name").

I wasn't making an argument about legality.

The Teller thing was a joke. Although your link raises a valid point. The restriction on needing two names lead to him providing a name which is not which not one he is normally identified by. If a cop were later to ask around for a guy called NLN (or perhaps even NLN Teller), nobody would know who they were referring to, however if they said Teller. Forcing two names, might just mean that instead of getting something generic or vague, you instead get something that is misleading.

As for the rest of the things you mentioned. We just have different opinions, so fair enough and thanks for your response anyway.
