### ISSUE TITLE
<Question>Custom Hook not detected

### ISSUE THREAD

**Issue by hirokihokari** [brigade/overcommit#425]
I follow the README and put **custom-script.sh** in .git-hooks directory. Then defined it in .overcommit.yml PrePush section as below:
```
  CustomHook:
    enabled: true
    required_executable: 'custom-hook'
```

When I tried to push, this comes out:
`Hook must specify a 'required_executable' or 'command' that is tracked by git (i.e. is a path relative to the root of the repository) so that it can be signed`

I'm not sure what I'm doing wrong.

**Comment by jawshooah** [comment]
`required_executable` should be the relative path from the repo root to the script. So in your case, it should be `./.git-hooks/custom-script.sh`

**Comment by sds** [comment]
Hey @hirokihokari,

As @jawshooah already mentioned, when referring to a file in your repository you must use a relative path.

The other option is to make sure the script/executable exposed can be found in one of the paths in your `PATH` environment variable, though that's likely not what you want in this specific case since you're referring to an executable in your repository.

Documentation for the `required_executable` option can be found under https://github.com/brigade/overcommit#hook-options. Hope this helps!

**Comment by hirokihokari** [comment]
@jawshooah @sds Thank you for the answers.
Silly me! The message REPEATEDLY mentions relative path and I misunderstood that the line `plugin_directory: '.git-hooks'` is taking care of it already. But then what exactly is the said line doing here?

**Comment by sds** [comment]
The `plugin_directory` option simply specifies the directory relative to the repository root (i.e. the value returned by `git rev-parse --show-toplevel`) where the hooks are stored. 

Perhaps you are confused why this doesn't need to be `./.git-hooks`? I agree this is perhaps odd. The main reason is that you can basically think of `required_executable` as being what you would need to type at a shell prompt. If you want to run a script that is in your current directory in *nix, you need to [prefix it with `./`](http://stackoverflow.com/a/6331085). 

Hope that explains things.
