### ISSUE TITLE
Small update to README.md for rootless mac users

### ISSUE THREAD

**Issue by phlippieb** [brigade/overcommit#433]
README.md suggests to install with the following command:
```
gem install overcommit
```

On OSX 10.11 and up, unless users have disabled rootless, the command will fail because RubyGems does not have access to `/usr/bin`. I worked around it by installing to `/usr/local/bin`, as follows:
```
gem install -n /usr/local/bin overcommit
```

This problem is not unique to overcommit, but if this is the first time someone runs into it (like I did), having this in the readme could save them some time 😄

**Comment by jawshooah** [comment]
@phlippieb It's generally a bad idea to install system-level gems on macOS. You should `brew install ruby` or use a Ruby version manager like [rbenv](https://github.com/rbenv/rbenv/) or [rvm](https://rvm.io/) to manage your own Ruby installs, or at the very least install with `--user-install`.

**Comment by sds** [comment]
Thanks for bringing this up, @phlippieb. 

I agree with @jawshooah here: it's bad practice to install gems to your system Ruby because it requires root permissions.

It's unfortunate that the very first thing most new Ruby users today are exposed to are problems like this, which require a level of understanding about the ecosystem that is unreasonable.

I've added some documentation in the installation section of the README that will hopefully clarify this for new users. Thanks for pointing it out!

**Comment by phlippieb** [comment]
Okay cool! I also agree, but unfortunately, I started off wrong and it has become too much of a hassle to fix it on my laptop. Thanks for taking my suggestion into consideration, and I think the update you made instead is better.
