### ISSUE TITLE
Merging with conflicts causes stashed code

### ISSUE THREAD

**Issue by jclif** [brigade/overcommit#440]
Every time I try to commit after resolving conflicts, if there are checks that fail, I see the following error:
```
Unable to restore working tree after pre-commit hooks run
```
Whenever I am merging a branch and resolving conflicts, it would be preferable for these checks to fail and leave my staged source unmolested .

**Comment by sds** [comment]
Hey @jclif,

Without more context I can't help you here. I've been able to resolve merge conflicts without losing changes, so the problem is not obviously one with Overcommit, at least from the information you've given.

While it's been a long time since I've heard of anyone running into the error you've described, reports in the past have typically been because of some sort of file watcher you have in the background (e.g. `grunt`) which makes changes to tracked files when you change other files. Since Overcommit stashes the _unstaged_ changes to your files, runs the pre-commit hooks, and then restores the unstaged changes, if during this process a file watcher detects the change and then modifies another file you might run into this issue since the stash cannot be re-applied.

You can try digging into what is actually failing by running Overcommit in debug mode (as mentioned in our [Contribution Guidelines](https://github.com/brigade/overcommit/blob/master/CONTRIBUTING.md). Thanks!

**Comment by jclif** [comment]
That's certainly fair. I didn't see any past bugs that seemed to deal with the specific set of situations where I'm seeing this error (I am not running any watcher processes that could potentially change my file system).

One reproducible situation involves adding a newly tracked file that generates a Rubocop offense. This always produces the following type of error:

<img width="1432" alt="screen shot 2016-10-05 at 1 10 46 pm" src="https://cloud.githubusercontent.com/assets/3463691/19123629/63c3f55e-8afd-11e6-89b5-16a471dad390.png">

**Comment by sds** [comment]
Can you run your `gca` comment (I'm assuming that's not doing anything except `git commit --amend`, correct?) with Overcommit debug mode enabled?

```bash
OVERCOMMIT_DEBUG=1 gca
```

That may help illuminate the problem.

**Comment by sds** [comment]
Closing due to lack of response. Feel free to reopen with the additional log output, but it sounds like this will require some investigation on your side in order to properly debug since we can't reproduce this ourselves. Thanks!
