### ISSUE TITLE
Unstaged rubocop.yml changes not taken into account

### ISSUE THREAD

**Issue by vemv** [brigade/overcommit#448]
Hi,

Say I have changes in rubocop.yml which I don't want to commit, temporarily. If I run `bundle exec rubocop`, the unstaged changes will of course being taken into account: rubocop rules will be interpreted as one can read them by opening rubocop.yml in an editor.

The same is not true when running rubocop through overcommit. If I want a rubocop rule (or deleted rule) to be taken into account, it has to be either committed or staged.

I do not want that behavior, and also it's a rather surprising one.

Could you provide an option to skip this behavior?

It'd greatly help transitioning from not using overcommit to using it (which isn't easy for a large team).

Cheers - Victor

**Comment by jawshooah** [comment]
We stash all unstaged changes before running pre-commit hooks specifically so that the unstaged changes will not be taken into account. What you're asking for is, unfortunately, contrary to a core part of how Overcommit works.

May I ask why you want to commit style changes in your code before you commit the changes in your config?

**Comment by vemv** [comment]
Yes I was suspecting this was due to the stashing. I've seen some other GH issues caused by this approach so maybe this 'core part' is unfortunately a flawed one? Could the new `git-worktree` be a better alternative?

> May I ask why you want to commit style changes in your code before you commit the changes in your config?

Bit hard to explain, and definitely I wouldn't want to deviate the conversation with an unrelated issue.
