### ISSUE TITLE
Problems locating overcommit binary

### ISSUE THREAD

**Issue by brandonweiss** [brigade/overcommit#454]
This is perhaps an unusual case, but I use rbenv to dynamically change my Ruby and gems depending on what project I'm working on. If I install overcommit for a specific Ruby version, and then use the GitHub Desktop app to make a commit, it can't find the overcommit binary because it's using the default/system Ruby of the OS.

It seems like Overcommit needs to be aware of the Ruby context? Or perhaps more simply it would be possible to specify the path to the overcommit binary when installing, that way the git hooks would know where to find it?

**Comment by proinsias** [comment]
@brandonweiss – I'm also using `rbenv`, and encountered similar issues. 

My workaround is to have a global (non-system) ruby version, and install `overcommit` there (as well as in whatever other ruby versions I might want to use it with). 

Then I include `eval "$(rbenv init -)";` in my `.bashrc` so that apps (this should include GUI apps) will use that ruby version instead of the system version. 

Would that work in your case?

**Comment by brandonweiss** [comment]
Not really… if it was just me it might be fine, but there's a whole team of people working on this repo and telling everyone they have to do this incantation in order for things to work is a shit experience and not acceptable. It sort of just has to work. But I appreciate the tip!

**Comment by sds** [comment]
Hey @brandonweiss,

This looks similar to #402, which suggests a potential workaround, though it's obviously not ideal.

Would appreciate a pull request from the community that properly addresses this issue, as this use case is not one that I personally have time to look into. Thanks!
