### ISSUE TITLE
Overcommit running on unstaged files

### ISSUE THREAD

**Issue by pcragone** [brigade/overcommit#510]
I'm having a problem where overcommit is running pre-commit checks on all files, not just the ones that are staged.  I can't seem to find a configuration to change this, but clearly I'm missing something - care to enlighten me?

Edit: Further investigation looks like it's including new files, rather than ignoring them.  Is there a way to get around this?

**Comment by sds** [comment]
Hey @pcragone, how are you invoking Overcommit here? If via `overcommit --run`, all pre-commit checks are run against _all_ files.

If this is truly being run in a pre-commit context (i.e. after running `git commit ...`), a reproducible example would be helpful here. Thanks!

**Comment by pcragone** [comment]
I'm just running it through the hook - `git commit`.

Lemme see if I can throw something together real quick.  H/o

**Comment by pcragone** [comment]
Ok I got something for you.

Clone this repository: [https://github.com/pcragone/overcommit_test](https://github.com/pcragone/overcommit_test)

Run `echo "module ExtraHelper; end" > app/helpers/extra_helper.rb`

Edit some file - say, change the title in `app/views/layouts/application.html.erb` to "Hello, World!"

Run `git add app/views/layouts/application.html.erb` (or whatever file you changed).  Be sure to leave the `app/helpers/extra_helper.rb` file alone.

Run `git commit`.  You should see it fail:

![image](https://user-images.githubusercontent.com/1450380/30190008-61959cc6-9405-11e7-87a6-df6fa9840d64.png)

**Comment by sds** [comment]
Thanks for providing a detailed example, @pcragone.

The issue here is not Overcommit but specifically the `RailsBestPractices` pre-commit hook. This [hook](https://github.com/brigade/overcommit/blob/v0.41.0/lib/overcommit/hook/pre_commit/rails_best_practices.rb) appears to run against all files regardless of which were edited (since I assume it needs to in order to have enough context to perform the static analysis it does).

Thus I would suggest you either disable it or accept that in order to perform its function it needs to run against all files. Hope this helps!

**Comment by pcragone** [comment]
Okie dokie!  Thanks!
