### ISSUE TITLE
Sharing Hooks Between Context

### ISSUE THREAD

**Issue by taufek** [brigade/overcommit#557]
Currently, we already able to do so. For example `ComposerInstall` module under `hooks/shared` folder is included in modules under `hooks/post-merge`, `hooks/post-checkout` and etc.

Advantage of this approach is, it is clear what are the available hooks under each folder. But the downside is you will need to duplicate those files under the supported folders. 

Now, it is also possible to share hooks under PreCommit with PrePush. If we want to share them with current approach, we will need to duplicate too many files. 

I’m thinking if there is a better way where we could reuse same hooks in different context without having to duplicate the files under different folders. 

One problem to achieve this is the way we load those hooks. It loads them by scanning the files under hooks directory. 

Since we have the`config/default.yml` that defines all hooks for all context, perhaps we could load those hooks based on this configurations. 

I hope this make sense. Would love to hear thoughts from you guys.

**Comment by sds** [comment]
Hey @taufek, please see the discussion in https://github.com/brigade/overcommit/issues/420#issuecomment-361043383 for the challenges with this. I'm going to close this in favor of the conversation there, as it has more context (as well as concrete action items required in order to get this to work).

Feel free to reopen if I've misunderstood what you're trying to accomplish here. Thanks!

**Comment by taufek** [comment]
Noted.
