### ISSUE TITLE
VS Code Tasks: 'overcommit' gem not installed

### ISSUE THREAD

**Issue by InTheCloudDan** [brigade/overcommit#558]
I have a tasks.json that runs some git commands that is failing.

```
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
error: failed to push some refs to 'xxx'
The terminal process terminated with exit code: 1
```

I have the overcommit gem installed so not sure why this is throwing an error.

**Comment by sds** [comment]
Hey @InTheCloudDan, there's not much information here to help diagnose this issue.

What executes `tasks.json`? Are you running this from a GUI application, or all within the terminal? Are you using `rbenv` to manage Ruby versions, or are you installing to the system Ruby. 

In short, this is not an Overcommit issue but a problem with your development environment and how it is configured. In this specific situation, the executable that `git` runs (`pre-push`, in your scenario) is running in an environment where Ruby is installed but that Ruby can't find the Overcommit gem. What happens when you run something like `overcommit --run` instead of `git push`? What does `which overcommit` say? How many versions of Ruby do you have installed? Is Overcommit installed on the versions you intend to be using in this situation?

**Comment by sds** [comment]
Apologies, I just realized "VS" in your title likely means Visual Studio, which means you're running a graphical application.

See https://github.com/brigade/overcommit/issues/402#issuecomment-279508653 for a workaround to ensure your GUI runs with the correct environment variables so that gems can be found. Thanks!
