### ISSUE TITLE
Force overcommit integration

### ISSUE THREAD

**Issue by Rob117** [brigade/overcommit#578]
Simply put, I installed overcommit with the --install command, ran it locally, and it worked well.

When my coworker tries to use it, he can commit code without pre-commit hooks running because he doesn't have the gem installed. Even specifying the Gemfile option and using bundle doesn't force the gem to be installed on his end.

Is there a way to prevent commits unless the gem is installed, or is that outside the scope of this library?

**Comment by sds** [comment]
Hey @Rob117, that's outside the scope of this library. Git hooks are opt-in by design—see the section on [Security](https://github.com/brigade/overcommit#security) for examples of why this is the case.

However, once someone has run `overcommit --install` in their local repository, they will start running the hooks going forward. 

Hope that helps!
