### ISSUE TITLE
After Branch Hook

### ISSUE THREAD

**Issue by ciembor** [brigade/overcommit#589]
I would like to have a hook that clones database (based on a branch name) after creating new branch. How could I write such hook? I don't see any documentation or section in readme for creating custom hooks.

**Comment by sds** [comment]
Hey @ciembor, I'm not really clear on what you're trying to accomplish, and there are a lot of questions about the kind of flow you'd like to support.

I would suggest that you keep hooks very simple. Considering how often you change branches, tying the `post-checkout` hook to cloning of a database sounds like a quick way to frustrate developers (since I assume it is a time-consuming process).

If you insist, I suggest you look at the current set of [`post-checkout` hooks](https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook/post_checkout) for some inspiration. Good luck!

**Comment by ciembor** [comment]
Thank you. It takes time, but I want to automise this process:
https://manas.tech/blog/2016/01/08/switching-rails-app-database-per-git-branch.html
I know it's time consuming, but it's even more time consuming if you do this manually :). 

But I digged deeper into git hooks, and I see that it's not possible to have a hook for `git branch` (first I thought I can have a hook for any command). So I will probably stay with a rake task :(.
