### ISSUE TITLE
`include` files based on e.g. shebang

### ISSUE THREAD

**Issue by harto** [brigade/overcommit#592]
What do you think about adding a way to `include` files based on their shebang (or some other classifier) rather than path globs?

My use case is that I have a `scripts` directory with scripts implemented in different languages. `scripts/foo` might be a node.js script, `scripts/bar` might be a bash script. It's therefore difficult to figure out how to e.g. find which files the `ShellCheck` hook should apply to.

I wonder if it would instead be possible to configure the ShellCheck hook to check modified files that started with some shebang matching a regexp, or something like that.

**Comment by sds** [comment]
Hey @harto, thanks for the suggestion.

Is there any reason you can't locate all of these executable scripts in a well-defined location? Your `include` statement could then just filter to all files in that directory, and then you can symlink them to wherever you would like them to be.

**Comment by harto** [comment]
That's an interesting suggestion. I guess the only problem might be if somebody added a new file outside of that well-defined directory structure — it might be nice to detect and check any file of a given type regardless of its location in the source tree. But, I don't know if we actually have that requirement in reality.

**Comment by sds** [comment]
Going to close as supporting this would require that we read the contents of every file in order to determine if it has a shebang, which could significantly slow down hook runs in large repositories. It's also an OS-specific feature, which we've tried to stay away from to date.

If you feel strongly, a pull request with a proposed solution would be best to continue the discussion. Thanks!
